### ISSUE TITLE
Draw.io Template for V4

### ISSUE THREAD

**Issue by chris2k2** [ddd-crew/bounded-context-canvas#11]
I didn't find a draw.io template for version 4. I think someone has already one and just needs to upload it. If not, I'll volunteer.

**Comment by NTCoding** [comment]
Hi @chris2k2.

I've submitted a new template to Miro which is awaiting approval but nothing that I am aware of for draw.io.

If you want to volunteer your efforts would be greatly appreciated. 

Thanks

**Comment by chris2k2** [comment]
Hi @NTCoding 

> I've submitted a new template to Miro which is awaiting approval but nothing that I am aware of for draw.io.

Awesome. I Just found the miro link for v3. Where can I find the proposal board?

> If you want to volunteer your efforts would be greatly appreciated.

Sure. 

> Thanks

Thank you guys, the canvas is awesome 👍 :)
