### ISSUE TITLE
clarification appreciated: design vs. documentation, canvas vs. context map

### ISSUE THREAD

**Issue by hofstef** [ddd-crew/bounded-context-canvas#14]
Hi all,

I have been using the Bounded Context Canvas (v2 and v3) a couple of times now. I wanted to ask the opinion of author(s) and other practitioners on (1) design vs. documentation and (2) differentiation between canvas and context map:

(1)	Do you (authors and community) use the canvas primarily as a design tool or as a documentation template? 

In [Nick’s original post](https://medium.com/nick-tune-tech-strategy-blog/modelling-bounded-contexts-with-the-bounded-context-design-canvas-a-workshop-recipe-1f123e592ab), filling out the canvas is part of a “design recipe”. In my practice as a facilitator, I mostly use the canvas as my personal “checklist”: I have the teams work out name, description, UL, relevant actors etc. while we go through the modeled scenarios. We capture everything on sticky notes while discussing candidate bounded contexts. The canvas itself is then used to document the findings. In one case, we used the Miro template. In three other cases, the teams preferred Confluence for documentation. The segments of the canvas became sections of the confluence page. 

(2)	Do you (authors and community) have recommendations how to deal with the overlap between the canvas and context maps?

The canvas (v4) segments “inbound communication” and “outbound communication” describe relationships between bounded contexts that could also be depicted in a context map. Since I don’t like to document the same information in two places, I usually leave everything blank in the canvas that can be put in a context map.

Thanks in advance four your opinions!

Stefan

**Comment by NTCoding** [comment]
Hi @hofstef,

The canvas is used in a variety of ways. I like to use Nat Pryce's distinction:

> I distinguish between “informational” and “aspirational” architecture docs. Informational docs describes how things *are*, and should be generated from or checked for consistency with the system. Aspirational docs are for aligning teams towards a common goal. Aspirations change.

When manually creating the canvas it should ideally be used as an aspirational design tool. When documenting an existing system, ideally the system describes itself. The folks at Software Park are working on such a tool called Contexture: https://github.com/Softwarepark/Contexture. I believe this is the future where systems will describe themselves.

There's also another important distinction: diagrams vs models. A model is structured data that can be presented in different views. So when describing and existing system, the Context Map and the Bounded Context Cavas are different views of the same model. The information is not duplicated just projected into multiple different views.

When designing a system (aspirational) the canvas is like a checklist reminding you to ask the right questions. If you've already created a context map then you can consider that the item is already checked off and no need to show it on the canvas. However, adding the context map patterns to the canvas allows you to zoom in and review the complete design of a single context all in one place, so there is some value in duplication. 

Some people did specifically ask why the context mapping patterns weren't on the previous version and I've also found it useful as a teaching tool to have the context mapping patterns on there. But they are totally optional. 

The canvas actually started out as a checklist and I kept refining it over the years until I tried it as a canvas to make it more structured and collaborative.

Cheers

**Comment by hofstef** [comment]
Thanks, @NTCoding ! 

As usual, your reply is on point and answers my questions.

I agree that the distinction between “informational” and “aspirational” is important because any kind of modeling activity is shaped by its purpose. And it is interesting to know that the canvas started with a checklist. 

Best

**Comment by mploed** [comment]
Hey @hofstef,
I agree with @NTCoding regarding context maps and the bounded context canvas. They are two different perspectives. The context map is an overview of the relationships between bounded contexts and teams including some governance aspects. the canvas on the other hand is a "drill down" into a bounded context whith additional elements. Of course there should be a consistency between both but it's the same as asking for consistency between various diagrams in the C4 model or in the arc42 views.

Best regards!
