### ISSUE TITLE
Miro Board / Template for v4

### ISSUE THREAD

**Issue by mploed** [ddd-crew/bounded-context-canvas#15]
Hi @NTCoding,
do you plan releasing a Miro Template for the new version or are you even working on one?

Best regards,
Michael

**Comment by NTCoding** [comment]
Hi @mploed.

Good question. I have submitted a template to the Miroverse a week or so ago for V4 of the canvas. So now it is just awaiting their review/approval process.

If you need a copy now let me know and I can give you access.

Cheers

**Comment by mploed** [comment]
That would be awesome. I would post the board backup of it on GitHub as well for those who want to upload it to their accounts.

**Comment by mploed** [comment]
Miro Board is now on Miroverse
