### ISSUE TITLE
Inconsistency between canvas and model traits worksheet

### ISSUE THREAD

**Issue by mploed** [ddd-crew/bounded-context-canvas#29]
In the current (and proposed next version) of the bounded context design canvas is an inconsistency between the examples in the domain roles section and the model traits worksheet.

The examples in the domain roles section mention an **analysis context**, however it is not described in the model traits worksheet what that actually is. The analysis context is also not mentioned in th blog by Alberto (is the linked one even the right one?) and the presentation by Rebecca.

We should either remote the analysis context from the examples or add it to the model traits worksheet.

**Comment by Max-Git** [comment]
I just noticed where the confusion comes from: Analysis and Audit model traits are synonyms. So, yeah, I'm gonna update the model traits worksheet and put Analysis/Audit instead. And same goes for Draft and Specifications, they're also synonyms.
The link to Cyrille's old blog post is still valid from my point of view. It describes really well the example Alberto used during his talk. It only just focus on 2 different model traits, though ("draft" vs "execution"). But those 2 model traits are quite recurring patterns that can be often observed during domain discovery sessions. The shopping cart (draft/specifications) vs order (execution) is an easy to understand example I often refer to when I need to explain model traits.

Thanks for the issue @mploed!

**Comment by Max-Git** [comment]
Fixed in [74af22f](https://github.com/ddd-crew/bounded-context-canvas/commit/74af22f28356da06c26c341d4c3275449caab5e0)
