### ISSUE TITLE
Adapt the French translation to v5

### ISSUE THREAD

**Issue by yellowbrickc** [ddd-crew/bounded-context-canvas#30]
The canvas has some new (and very valuable) content which needs to be translated in French: https://github.com/ddd-crew/bounded-context-canvas/pull/28

Thank you 👍

**Comment by Max-Git** [comment]
I own the Miro board, I'm gonna do this!

**Comment by yellowbrickc** [comment]
You mean the French miro-board, do you? (not any of these #31 )

**Comment by Max-Git** [comment]
This is what I do mean, yes :)

**Comment by Max-Git** [comment]
Fixed by [ad2bd54](https://github.com/ddd-crew/bounded-context-canvas/commit/ad2bd54db270a409dd98a7c7f0e64a877e916e79)
