### ISSUE TITLE
HTML version without requiring browser extensions

### ISSUE THREAD

**Issue by FND** [ddd-crew/bounded-context-canvas#33]
Currently the [HTML version](https://github.com/ddd-crew/bounded-context-canvas/tree/master/tools/html-version) requires a browser extension for saving, which seems like a significant hurdle. This probably isn't necessary though: There are now standardized [APIs for accessing the file system](https://web.dev/file-system-access/) from JavaScript.

I have a [simplistic demo](https://fnd.github.io/automemo) demonstrating that. It [uses the aforementioned APIs](https://github.com/FND/automemo/blob/2da47dc78c22b335a9d4ec8da11b02a7965c49d0/src/fs.js) where available or [generates a download link](https://github.com/FND/automemo/blob/2da47dc78c22b335a9d4ec8da11b02a7965c49d0/src/html.js#L4) for other browsers, [TiddlyWiki](https://tiddlywiki.com/)-style. (Indeed, the latter might be sufficient in this case.)

**Comment by yellowbrickc** [comment]
Thank you @FND 👍 
Could you create a PR for this?
