### ISSUE TITLE
Request for clarification about core, supporting and generic domains

### ISSUE THREAD

**Issue by alexlundborgopticon** [ddd-crew/bounded-context-canvas#6]
Hi!
I'm new to DDD and would like to know more about the terms core, supporting and generic domains. What exactly is meant by "key strategic initiative" and "differentiator"? How can you tell what category a certain domain belongs to?
Thanks

**Comment by NTCoding** [comment]
Hi @alexlundborgopticon,

Welcome to the world of DDD! 

Could you let me know if these 2 resources are helpful at answering your questions?

- https://github.com/ddd-crew/core-domain-charts
- https://medium.com/nick-tune-tech-strategy-blog/core-domain-patterns-941f89446af5

Nick

**Comment by alexlundborgopticon** [comment]
Those where helpful, thank you!
